# Generated by Django 6.0.3 on 2026-03-21 12:28

import apps.applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_code', models.CharField(default=apps.applications.models.generate_candidate_code, max_length=20, unique=True)),
                ('cover_letter', models.TextField()),
                ('resume_file', models.FileField(upload_to='resumes/%Y/%m/')),
                ('resume_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('graded', 'Graded'), ('shortlisted', 'Shortlisted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualification_score', models.IntegerField(default=0)),
                ('experience_score', models.IntegerField(default=0)),
                ('skills_score', models.IntegerField(default=0)),
                ('cover_letter_score', models.IntegerField(default=0)),
                ('overall_score', models.IntegerField(default=0)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('summary', models.TextField(blank=True)),
                ('strengths', models.JSONField(default=list)),
                ('gaps', models.JSONField(default=list)),
                ('graded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
